server:
  port: 8080

# 数据库
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spider?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# 主要是配置该属性
mybatis-plus:
  mapper-locations: classpath:com/ws/study/springboot/mybatis/*/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
#执行 SQL 分析打印
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

